circumvent: use psiphon-console-client from AUR

diff --git a/scripts/.local/bin/daemons/circumvent b/scripts/.local/bin/daemons/circumvent
--- a/scripts/.local/bin/daemons/circumvent
+++ b/scripts/.local/bin/daemons/circumvent
@@ -1,29 +1,22 @@
 #!/bin/sh
-# download, configure and start the psiphon proxy client.
-# requires curl, libnotify(optional), firejail and firejail's circumvent profile.
+# configure and start the psiphon proxy client.
+# requires psiphon-console-client(AUR), curl, firejail, firejail's circumvent profile and libnotify(optional).
 
 # Config
 # ==========
 # ports
-socks_port=9050
-http_port=8585
-#
+SOCKS_PORT=9050
+HTTP_PORT=8585
 # where to put the psiphon binary and configs
-dir=~/.local/share/circumvent
-#
-# psiphon-client's github path
-repo=Psiphon-Labs/psiphon-tunnel-core-binaries # name of the github repository
-path=linux/psiphon-tunnel-core-x86_64 # path of the file in the repository
-#
-# name of psiphon's binary
-bin=psiphon-client
+DATA_DIR=~/.local/share/circumvent
 # ==========
 
 main() {
+    unset VERBOSE
+    case $1 in -v|--verbose) VERBOSE=true ;; esac
     wait_for_internet
-    check_for_updates
     gen_psiphon_configs
-    start "$1"
+    start_psiphon
 }
 
 # if NetworkManager is available, use it to wait until we have internet
@@ -36,50 +29,29 @@ wait_for_internet() {
         done
     fi
 }
-#--whitelist="$dir" --x11=none --disable-mnt --private-tmp \
+
 # start psiphon
-start() {
-    echo starting "$bin"...
-    pidof -qx "$bin" && die "another instance of $bin is running."
+start_psiphon() {
+    echo starting psiphon...
+    pidof -qx psiphon-console-client && die 'another instance of psiphon-console-client is running.'
     trap 'echo exiting...; pkill -P$$' HUP INT TERM
-    firejail --profile=circumvent "$dir/$bin" -config "$dir"/config -dataRootDirectory "$dir" 2>&1 |
+    firejail --profile=circumvent psiphon-console-client -config "$DATA_DIR"/config.json -dataRootDirectory "$DATA_DIR" 2>&1 |
         while IFS= read -r line; do
-            case $1 in -v|--verbose) printf '%s\n' "$line" ;; esac
+            [ "$VERBOSE" = true ] && printf '%s\n' "$line"
             case $line in
             *Tunnels*)
-                curl -s --socks5 localhost:$socks_port ping.archlinux.org >/dev/null && {
-                    echo "$bin" connected.
+                curl -s --socks5 localhost:$SOCKS_PORT ping.archlinux.org >/dev/null && {
+                    echo psiphon connected.
                     notify-send Circumvent Connected.
                 }
             ;;
             *PortInUse*)
-                die "one of the ports ($socks_port, $http_port) is in use, probably by Tor."
+                die "one of the ports ($SOCKS_PORT, $HTTP_PORT) is in use, probably by Tor."
             ;;
             esac
     done &
-    echo "$bin" started, connecting...
+    echo psiphon started, connecting...
     wait
-}
-
-# update psiphon if a newer version is available
-check_for_updates() {
-    echo checking for updates...
-    apiurl="https://api.github.com/repos/$repo/commits?path=$(echo "$path" | sed 's|/|%2F|g')&page=1&per_page=1"
-    lastcommit=$(curl -fsL "$apiurl" | grep -m1 '^\s\+"date":' | cut -d\" -f4 | xargs -r date +%s -d)
-    filebirth=$(stat -c%W "$dir/$bin")
-    if [ ! -f "$dir/$bin" ] || [ "$lastcommit" -gt "$filebirth" ]; then
-        echo "a new commit at $lastcommit is newer than $bin's birth at $filebirth."
-        update
-    fi
-    chmod 755 "$dir/$bin"
-}
-
-update() {
-    echo updating...
-    url="https://raw.githubusercontent.com/$repo/master/$path"
-    mkdir -p "$dir" || die "couldn't make directory $dir."
-    aria2c -k1M -x5 -d"$dir" -o"$bin.new" "$url" &&
-        mv "$dir/$bin.new" "$dir/$bin"
 }
 
 die() {
@@ -91,10 +63,10 @@ die() {
 # generate psiphon's config file
 gen_psiphon_configs() {
     echo writing the config file...
-    cat << eof > "$dir"/config || die "failed to write psiphon's config."
+    cat << EOF > "$DATA_DIR"/config.json || die "failed to write psiphon's config."
 {
-    "LocalHttpProxyPort": $http_port,
-    "LocalSocksProxyPort": $socks_port,
+    "LocalHttpProxyPort": $HTTP_PORT,
+    "LocalSocksProxyPort": $SOCKS_PORT,
     "SponsorId": "FFFFFFFFFFFFFFFF",
     "PropagationChannelId": "FFFFFFFFFFFFFFFF",
     "RemoteServerListSignaturePublicKey": "MIICIDANBgkqhkiG9w0BAQEFAAOCAg0AMIICCAKCAgEAt7Ls+/39r+T6zNW7GiVpJfzq/xvL9SBH5rIFnk0RXYEYavax3WS6HOD35eTAqn8AniOwiH+DOkvgSKF2caqk/y1dfq47Pdymtwzp9ikpB1C5OfAysXzBiwVJlCdajBKvBZDerV1cMvRzCKvKwRmvDmHgphQQ7WfXIGbRbmmk6opMBh3roE42KcotLFtqp0RRwLtcBRNtCdsrVsjiI1Lqz/lH+T61sGjSjQ3CHMuZYSQJZo/KrvzgQXpkaCTdbObxHqb6/+i1qaVOfEsvjoiyzTxJADvSytVtcTjijhPEV6XskJVHE1Zgl+7rATr/pDQkw6DPCNBS1+Y6fy7GstZALQXwEDN/qhQI9kWkHijT8ns+i1vGg00Mk/6J75arLhqcodWsdeG/M/moWgqQAnlZAGVtJI1OgeF5fsPpXu4kctOfuZlGjVZXQNW34aOzm8r8S0eVZitPlbhcPiR4gT/aSMz/wd8lZlzZYsje/Jr8u/YtlwjjreZrGRmG8KMOzukV3lLmMppXFMvl4bxv6YFEmIuTsOhbLTwFgh7KYNjodLj/LsqRVfwz31PgWQFTEPICV7GCvgVlPRxnofqKSjgTWI4mxDhBpVcATvaoBl1L/6WLbFvBsoAUBItWwctO2xalKxF5szhGm8lccoc5MZr8kfE0uxMgsxz4er68iCID+rsCAQM=",
@@ -121,7 +93,7 @@ gen_psiphon_configs() {
         }
     ]
 }
-eof
+EOF
 }
 
 main "$@"
