massively improve the live script

diff --git a/scripts/.local/bin/other/live b/scripts/.local/bin/other/live
--- a/scripts/.local/bin/other/live
+++ b/scripts/.local/bin/other/live
@@ -11,7 +11,7 @@
 #   $ live
 
 # config
-script_name='live'
+pid="${XDG_RUNTIME_DIR:-/tmp}/live.pid"
 mpv_args='
 --fullscreen
 --loop-file
@@ -26,66 +26,92 @@ mpv_args='
 -wid WID
 '
 
-main ()
+main()
 {
+    [ -z "$*" ] && kill_other_instances && exit
     wallpaper="$1"
-    kill_other_instances
-    set_wallpaper_all_displays "$wallpaper"
+    error_checks
+    fork "$@"
+    manage_instances
+    set_wallpaper_all_displays
+}
+
+set_wallpaper_all_displays()
+{
+    for display_geometry in $(get_display_geometries); do
+        set_wallpaper &
+    done
     wait
 }
 
-kill_other_instances ()
+set_wallpaper()
 {
-    [ -n "$wallpaper" ] && error_checks
-    pkill -x --older 1 --signal USR1 "$script_name"
-    [ -z "$wallpaper" ] && exit
-    trap exit USR1
-    trap 'kill -- -$$' EXIT HUP
-}
-
-set_wallpaper_all_displays ()
-{
-    local wallpaper="$1"
-    for display_geometry in $(get_display_geometries); do
-        set_wallpaper "$display_geometry" "$wallpaper" &
-    done
-}
-
-set_wallpaper ()
-{
-    local display_geometry="$1"
-    local wallpaper="$2"
     xwinwrap -ov -ni -g "$display_geometry" -- \
         mpv $(mpv_args) "$wallpaper" >/dev/null 2>&1
 }
 
-get_display_geometries ()
+get_display_geometries()
 {
     xrandr -q | grep ' connected' |
         grep --only-matching --perl-regexp '\d+x\d+\+\d+\+\d+'
 }
 
-error_checks ()
-{
-    [ ! -r "$wallpaper" ] &&
-        echo bad file given >&2 &&
-        exit 1
-
-    [ -z "$DISPLAY" ] &&
-        echo no display >&2 &&
-        exit 1
-}
-
-mpv_wid ()
+mpv_wid()
 {
     wid="$1"
     shift
     mpv $(mpv_args) --wid="$wid" "$@"
 }
 
-mpv_args ()
+mpv_args()
 {
-    echo "$mpv_args" | tr '\n' ' '
+    printf '%s\n' "$mpv_args" | tr '\n' ' '
+}
+
+manage_instances()
+{
+    kill_other_instances
+    echo $$ > "$pid" || exit 1
+    trap exit USR1
+    trap "rm '$pid'; kill 0" EXIT
+}
+
+kill_other_instances()
+{
+    [ -r "$pid" ] && kill -USR1 "$(cat "$pid")" ||
+        echo no other instances running. >&2
+    return 0
+}
+
+fork()
+{
+    [ "$FORKED" = true ] && return
+    export FORKED=true
+    setsid -f "$0" "$@" >/dev/null 2>&1
+    exit
+}
+
+error_checks()
+{
+    [ ! -r "$wallpaper" ] && die "cannot read file: $wallpaper"
+    [ -z "$DISPLAY" ] && die "no display detected"
+    check_deps xrandr xwinwrap mpv
+}
+
+check_deps()
+{
+    for prog in "$@"; do
+        command -v $prog >/dev/null || {
+            die dependency not installed: $prog
+            return 1
+        }
+    done
+}
+
+die()
+{
+    printf '%s\n' "live: $*" >&2
+    exit 1
 }
 
 main "$@"
